// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 insertVector() ", "[example]")
{
	const int SIZE = 10;
	int usernum, idx;
	vector<int> number(10);

	srand(time(0));
	makeVector(number);
	printVector(number);
	usernum = 15;
	for (int i = 0; i < number.size(); i++)
	{
		if (number[i] > usernum)
		{
			idx = i;
			break;
		}
	}
	insertVector(number, usernum);
	printVector(number);

	REQUIRE(number[idx] == usernum);
}
// tests for exercise 2
TEST_CASE("Ex2 deleteVector()", "[example]")
{
	const int SIZE = 30;
	int usernum, delcnt, result;
	int cnt = 0;
	vector<int> number(SIZE);
	vector<int>::iterator iter;

	srand(time(0));
	makeVector(number);
	printVector(number);
	usernum = number[2];
	delcnt = count(number.begin(), number.end(), usernum);
	cout << " deleted count shoudl be " << delcnt << endl;
	result = deleteVector(number, usernum);

	REQUIRE(delcnt == result);
}